blender_version_min = "3.6.0"
id = "Stagehand"
maintainer = "nick"
license = ["to be defined"]
name = "Stagehand"
schema_version = "1.0.0"
tagline = "descrizione del programma"
type = "add-on"
version = "0.0.13"

[permissions]
network = "Check GitHub Releases and download Stagehand addon updates"
